# Generated by Django 5.1 on 2026-03-19 17:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_revenue_report', 'Can view revenue report'), ('view_occupancy_report', 'Can view occupancy report'), ('view_guest_report', 'Can view guest analytics report'), ('view_today_overview', 'Can view today overview report'), ('view_room_performance_report', 'Can view room performance report'), ('view_reservation_report', 'Can view reservation fulfillment report'), ('view_clv_report', 'Can view customer lifetime value report'), ('view_trends_report', 'Can view seasonal trends report'), ('view_stay_duration_report', 'Can view stay duration report'), ('view_upsell_report', 'Can view extra bed upsell report'), ('view_pipeline_report', 'Can view booking pipeline report'), ('view_pl_report', 'Can view P&L report'), ('view_staff_sales_report', 'Can view staff sales report'), ('view_cash_reconciliation', 'Can view cash reconciliation'), ('view_expense_report', 'Can view expense report')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=7)),
                ('charge_type', models.CharField(choices=[('flat', 'Flat'), ('per_night', 'Per Night')], default='flat', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('value', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('beds', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_withdrawals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('trans', 'TRANS'), ('other', 'OTHER')], max_length=6)),
                ('identity_card_1', models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpeg', 'jpg', 'png']), management.models.validate_file_size])),
                ('identity_card_2', models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpeg', 'jpg', 'png']), management.models.validate_file_size])),
                ('date_of_birth', models.DateField(null=True)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.countrycodes')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=7)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='management.group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='management.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='RoomStayLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(null=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=7)),
                ('extra_bed', models.PositiveSmallIntegerField(default=0)),
                ('extra_per_bed_price', models.DecimalField(decimal_places=0, default=0, max_digits=7)),
                ('is_nc', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='management.group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='management.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='RoomNCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('stay_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nc_requests', to='management.roomstaylogs')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_processed', to=settings.AUTH_USER_MODEL)),
                ('stay_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='management.roomstaylogs')),
            ],
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='management.roomtype'),
        ),
        migrations.CreateModel(
            name='StayLogAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage', to='management.amenity')),
                ('stay_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='management.roomstaylogs')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='management.customers')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='management.group')),
            ],
            options={
                'unique_together': {('group', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='RoomsPriceChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=7)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_chart', to='management.rooms')),
            ],
            options={
                'unique_together': {('room', 'date')},
            },
        ),
    ]
