# Generated by Django 5.1 on 2024-08-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="CounterCodes", new_name="CountryCodes",),
    ]
