# Generated by Django 5.1 on 2024-12-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_rename_countercodes_countrycodes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rooms",
            name="room_number",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="roomstaylogs",
            name="extra_per_bed_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="roomstaylogs",
            name="price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
    ]
