# Generated by Django 5.1 on 2024-12-13 05:35

import django.core.validators
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_rooms_room_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="identity_card_1",
            field=models.FileField(
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpeg", "jpg", "png"]
                    ),
                    management.models.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customers",
            name="identity_card_2",
            field=models.FileField(
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpeg", "jpg", "png"]
                    ),
                    management.models.validate_file_size,
                ],
            ),
        ),
    ]
