# Generated by Django 5.1 on 2026-03-30 08:34

import django.core.validators
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_customers_optional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='identity_card_1',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpeg', 'jpg', 'png']), management.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='customers',
            name='identity_card_2',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpeg', 'jpg', 'png']), management.models.validate_file_size]),
        ),
    ]
