# Generated by Django 5.1 on 2026-04-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_customers_optional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomstaylogs',
            name='is_ac',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
