# Generated by Django 5.1 on 2026-04-01 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_roomstaylogs_is_ac'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.PositiveSmallIntegerField()),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='management.reservation')),
            ],
        ),
    ]
