# Generated by Django 5.1 on 2026-04-01 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_reminder_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservationreminder',
            unique_together={('reservation', 'days_before')},
        ),
        migrations.AddField(
            model_name='reservationreminder',
            name='dismissed_by',
            field=models.ManyToManyField(blank=True, related_name='dismissed_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='reservationreminder',
            name='is_dismissed',
        ),
        migrations.RemoveField(
            model_name='reservationreminder',
            name='user',
        ),
    ]
