# Generated by Django 5.1 on 2026-04-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_reminder_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('cleaning', 'Cleaning'), ('out_of_order', 'Out of Order')], default='available', max_length=15),
        ),
        migrations.AddField(
            model_name='roomstaylogs',
            name='gst_inclusive',
            field=models.BooleanField(default=False),
        ),
    ]
