# Generated by Django 5.1 on 2026-04-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_room_status_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='advance_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='reservation',
            name='advance_payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=10),
        ),
    ]
