# Generated by Django 5.1 on 2026-04-30 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0021_foodorder_food_gst_inclusive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportpermissions",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("view_revenue_report", "Can view revenue report"),
                    ("view_occupancy_report", "Can view occupancy report"),
                    ("view_guest_report", "Can view guest analytics report"),
                    ("view_today_overview", "Can view today overview report"),
                    (
                        "view_room_performance_report",
                        "Can view room performance report",
                    ),
                    (
                        "view_reservation_report",
                        "Can view reservation fulfillment report",
                    ),
                    ("view_clv_report", "Can view customer lifetime value report"),
                    ("view_trends_report", "Can view seasonal trends report"),
                    ("view_stay_duration_report", "Can view stay duration report"),
                    ("view_upsell_report", "Can view extra bed upsell report"),
                    ("view_pipeline_report", "Can view booking pipeline report"),
                    ("view_pl_report", "Can view P&L report"),
                    ("view_staff_sales_report", "Can view staff sales report"),
                    ("view_cash_reconciliation", "Can view cash reconciliation"),
                    ("view_expense_report", "Can view expense report"),
                    ("view_cancellation_report", "Can view cancellation report"),
                ],
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rooms",
            name="cancellation_fee",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name="rooms",
            name="overtime_fee",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name="roomstaylogs",
            name="overtime_fee_charged",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=7, null=True
            ),
        ),
        migrations.CreateModel(
            name="CancellationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cancellation_type",
                    models.CharField(
                        choices=[
                            ("checkin", "Check-in"),
                            ("reservation", "Reservation"),
                        ],
                        max_length=15,
                    ),
                ),
                ("room_number", models.CharField(max_length=10)),
                ("reason", models.TextField()),
                (
                    "cancellation_fee",
                    models.DecimalField(decimal_places=0, default=0, max_digits=7),
                ),
                ("cancelled_on", models.DateTimeField(auto_now_add=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancellations_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancellations",
                        to="management.group",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancellations",
                        to="management.reservation",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancellation_logs",
                        to="management.rooms",
                    ),
                ),
                (
                    "stay_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancellations",
                        to="management.roomstaylogs",
                    ),
                ),
            ],
        ),
    ]
