# Generated by Django 5.1 on 2026-04-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0022_cancellation_fees_and_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancellationlog",
            name="default_fee",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
    ]
