# Generated by Django 5.1 on 2026-04-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0024_overtime_fee_default_and_checkout_by"),
    ]

    operations = [
        migrations.RemoveField(model_name="cashwithdrawal", name="reviewed_by",),
        migrations.RemoveField(model_name="cashwithdrawal", name="reviewed_on",),
        migrations.RemoveField(model_name="cashwithdrawal", name="status",),
    ]
