# Generated by Django 5.1 on 2026-05-01 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_reservation_advances(apps, schema_editor):
    Reservation = apps.get_model("management", "Reservation")
    ReservationPayment = apps.get_model("management", "ReservationPayment")

    seen = set()
    rows = (
        Reservation.objects.filter(advance_amount__gt=0, advance_payment_method__isnull=False)
        .values("group_id", "advance_amount", "advance_payment_method_id")
        .distinct()
    )
    for row in rows:
        key = (row["group_id"], row["advance_amount"], row["advance_payment_method_id"])
        if key in seen:
            continue
        seen.add(key)
        ReservationPayment.objects.create(
            group_id=row["group_id"],
            amount=row["advance_amount"],
            payment_method_id=row["advance_payment_method_id"],
            note="Migrated reservation advance",
        )


def remove_migrated_reservation_advances(apps, schema_editor):
    ReservationPayment = apps.get_model("management", "ReservationPayment")
    ReservationPayment.objects.filter(note="Migrated reservation advance").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0026_cancellationrefund"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=10)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_payments",
                        to="management.group",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_payments",
                        to="management.paymentmethod",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservation_payments_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrate_reservation_advances, remove_migrated_reservation_advances),
    ]
