# Generated by Django 5.1 on 2026-05-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0027_reservationpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="applied_advance",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="reservation",
            name="is_converted",
            field=models.BooleanField(default=False),
        ),
    ]
