# Generated by Django 5.1 on 2026-05-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0028_reservation_converted_and_applied_advance"),
    ]

    operations = [
        migrations.AddField(
            model_name="rooms",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
