# Generated by Django 5.1 on 2026-05-03 06:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0029_room_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("payment_received", "Payment Received"),
                            ("food_payment", "Food Payment"),
                            ("reservation_advance", "Reservation Advance"),
                            ("advance_applied", "Advance Applied at Check-in"),
                            ("expense_paid", "Expense Paid"),
                            ("cash_withdrawal", "Cash Withdrawal"),
                            ("refund_paid", "Refund Paid"),
                            ("cancellation_fee", "Cancellation Fee Kept"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=10)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "cancellation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="money_events",
                        to="management.cancellationlog",
                    ),
                ),
                (
                    "food_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="money_events",
                        to="management.foodorder",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="money_events",
                        to="management.paymentmethod",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="money_events_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="money_events",
                        to="management.reservation",
                    ),
                ),
                (
                    "stay_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="money_events",
                        to="management.roomstaylogs",
                    ),
                ),
            ],
        ),
    ]
