# Generated by Django 5.1 on 2026-05-03 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0030_moneyevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportpermissions",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("view_revenue_report", "Can view revenue report"),
                    ("view_occupancy_report", "Can view occupancy report"),
                    ("view_guest_report", "Can view guest analytics report"),
                    ("view_today_overview", "Can view today overview report"),
                    (
                        "view_room_performance_report",
                        "Can view room performance report",
                    ),
                    (
                        "view_reservation_report",
                        "Can view reservation fulfillment report",
                    ),
                    ("view_clv_report", "Can view customer lifetime value report"),
                    ("view_trends_report", "Can view seasonal trends report"),
                    ("view_stay_duration_report", "Can view stay duration report"),
                    ("view_upsell_report", "Can view extra bed upsell report"),
                    ("view_pipeline_report", "Can view booking pipeline report"),
                    ("view_pl_report", "Can view P&L report"),
                    ("view_staff_sales_report", "Can view staff sales report"),
                    ("view_cash_reconciliation", "Can view cash reconciliation"),
                    ("view_expense_report", "Can view expense report"),
                    ("view_cancellation_report", "Can view cancellation report"),
                    ("view_daily_settlement", "Can view daily settlement"),
                    ("manage_daily_settlement", "Can settle/manage daily settlement"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailySettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("settled", "Settled")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "snap_room_payments",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "snap_food_payments",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "snap_reservation_advances",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "snap_direct_cancellation_fees",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "snap_total_inflow",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "snap_expenses",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "snap_withdrawals",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "snap_refunds",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "snap_total_outflow",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "snap_net",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "settled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlements_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SettlementMethodBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_inflow",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "system_outflow",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "actual_received",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=12, null=True
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_breakdowns",
                        to="management.paymentmethod",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="method_breakdowns",
                        to="management.dailysettlement",
                    ),
                ),
            ],
            options={"unique_together": {("settlement", "payment_method")},},
        ),
    ]
