# Generated by Django 5.1 on 2026-05-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0033_amenity_added_by_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashwithdrawal",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("debit", "Debit (Withdrawal)"),
                    ("credit", "Credit (Deposit)"),
                ],
                default="debit",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="moneyevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("payment_received", "Payment Received"),
                    ("food_payment", "Food Payment"),
                    ("reservation_advance", "Reservation Advance"),
                    ("advance_applied", "Advance Applied at Check-in"),
                    ("expense_paid", "Expense Paid"),
                    ("cash_withdrawal", "Cash Withdrawal"),
                    ("cash_deposit", "Cash Deposit"),
                    ("refund_paid", "Refund Paid"),
                    ("cancellation_fee", "Cancellation Fee Kept"),
                ],
                max_length=30,
            ),
        ),
    ]
