# Generated by Django 5.1 on 2026-05-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0034_cash_withdrawal_entry_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailysettlement",
            name="snap_cash_deposits",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
