# Generated by Django 5.1 on 2026-05-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0035_settlement_cash_deposits"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomstaylogs",
            name="actual_check_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
