# Generated by Django 5.1 on 2026-08-02 18:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_expense_category_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reportpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_revenue_report', 'Can view revenue report'), ('view_occupancy_report', 'Can view occupancy report'), ('view_guest_report', 'Can view guest analytics report'), ('view_today_overview', 'Can view today overview report'), ('view_room_performance_report', 'Can view room performance report'), ('view_reservation_report', 'Can view reservation fulfillment report'), ('view_clv_report', 'Can view customer lifetime value report'), ('view_trends_report', 'Can view seasonal trends report'), ('view_stay_duration_report', 'Can view stay duration report'), ('view_upsell_report', 'Can view extra bed upsell report'), ('view_pipeline_report', 'Can view booking pipeline report'), ('view_pl_report', 'Can view P&L report'), ('view_staff_sales_report', 'Can view staff sales report'), ('view_cash_reconciliation', 'Can view cash reconciliation'), ('view_expense_report', 'Can view expense report'), ('view_income_report', 'Can view income report'), ('view_cancellation_report', 'Can view cancellation report'), ('view_daily_settlement', 'Can view daily settlement'), ('manage_daily_settlement', 'Can settle/manage daily settlement')]},
        ),
        migrations.AddField(
            model_name='dailysettlement',
            name='snap_other_income',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='moneyevent',
            name='event_type',
            field=models.CharField(choices=[('payment_received', 'Payment Received'), ('food_payment', 'Food Payment'), ('reservation_advance', 'Reservation Advance'), ('advance_applied', 'Advance Applied at Check-in'), ('expense_paid', 'Expense Paid'), ('other_income', 'Other Income'), ('cash_withdrawal', 'Cash Withdrawal'), ('cash_deposit', 'Cash Deposit'), ('refund_paid', 'Refund Paid'), ('cancellation_fee', 'Cancellation Fee Kept')], max_length=30),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='management.paymentmethod')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='management.incomecategory')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='income_attachments/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='management.income')),
            ],
        ),
    ]
