# Generated by Django 5.1 on 2026-10-09 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_incomecategory_alter_reportpermissions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_revenue_report', 'Can view revenue report'), ('view_occupancy_report', 'Can view occupancy report'), ('view_guest_report', 'Can view guest analytics report'), ('view_today_overview', 'Can view today overview report'), ('view_room_performance_report', 'Can view room performance report'), ('view_reservation_report', 'Can view reservation fulfillment report'), ('view_clv_report', 'Can view customer lifetime value report'), ('view_trends_report', 'Can view seasonal trends report'), ('view_stay_duration_report', 'Can view stay duration report'), ('view_upsell_report', 'Can view extra bed upsell report'), ('view_pipeline_report', 'Can view booking pipeline report'), ('view_pl_report', 'Can view P&L report'), ('view_staff_sales_report', 'Can view staff sales report'), ('view_cash_reconciliation', 'Can view cash reconciliation'), ('view_expense_report', 'Can view expense report'), ('view_income_report', 'Can view income report'), ('view_cancellation_report', 'Can view cancellation report'), ('view_pending_dues_report', 'Can view pending dues report'), ('view_daily_settlement', 'Can view daily settlement'), ('manage_daily_settlement', 'Can settle/manage daily settlement')]},
        ),
    ]
