# Generated by Django 5.1 on 2026-10-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_pending_dues_report_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomstaylogs',
            name='gst_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
