# Generated by Django 5.1 on 2026-10-09 05:49

import django.db.models.deletion
from django.db import migrations, models


def link_existing_income(apps, schema_editor):
    """Match each Income to the unlinked other_income event it created (same date, amount, method, note)."""
    Income = apps.get_model('management', 'Income')
    MoneyEvent = apps.get_model('management', 'MoneyEvent')
    for inc in Income.objects.order_by('created_on'):
        ev = MoneyEvent.objects.filter(
            event_type='other_income', income__isnull=True,
            date=inc.date, amount=inc.amount,
            payment_method_id=inc.payment_method_id, note=inc.description,
        ).order_by('created_on').first()
        if ev:
            ev.income_id = inc.id
            ev.save(update_fields=['income'])


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_roomstaylogs_gst_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyevent',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_events', to='management.income'),
        ),
        migrations.RunPython(link_existing_income, migrations.RunPython.noop),
    ]
