# Generated by Django 5.1 on 2026-10-09 05:51

import django.db.models.deletion
from django.db import migrations, models


def link_existing_expenses(apps, schema_editor):
    """Match each Expense to the unlinked expense_paid event it created (same date, amount, method, note)."""
    Expense = apps.get_model('management', 'Expense')
    MoneyEvent = apps.get_model('management', 'MoneyEvent')
    for exp in Expense.objects.order_by('created_on'):
        ev = MoneyEvent.objects.filter(
            event_type='expense_paid', expense__isnull=True,
            date=exp.date, amount=exp.amount,
            payment_method_id=exp.payment_method_id, note=exp.description,
        ).order_by('created_on').first()
        if ev:
            ev.expense_id = exp.id
            ev.save(update_fields=['expense'])


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_moneyevent_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyevent',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_events', to='management.expense'),
        ),
        migrations.RunPython(link_existing_expenses, migrations.RunPython.noop),
    ]
