from django.urls import path
from .views import (RoomTypeListCreate, RoomTypeDetail, RoomListCreate, RoomDetail, RoomStatusLogList,
                    CountryCodeListCreate, CountryCodeDetail, CustomerListCreate, CustomerDetail,
                    ConfigurationListCreate, ConfigurationDetail, Checkin, Checkout,
                    RoomsPriceChartListCreate, RoomsPriceChartDetail, StayLogListActive, StayLogDetail,
                    group_customer, add_customers_to_group, remove_customer_from_group,
                    GroupCustomersView, ReservationListCreate, ReservationDetail,
                    AmenityListCreate, AmenityDetail, StayLogAmenityListCreate, StayLogAmenityDetail,
                    RevenueReportView, OccupancyReportView, GuestReportView,
                    TodayOverviewView, UserPermissionsView,
                    RoomPerformanceView, ReservationFulfillmentView, CLVReportView,
                    TrendsReportView, StayDurationView, UpsellReportView, PipelineReportView,
                    NcRequestListCreate, NcRequestDetail, NcRequestApprove, NcRequestReject,
                    StayLogPaymentListCreate, StayLogPaymentDetail,
                    CashWithdrawalListCreate, CashWithdrawalDetail, CashWithdrawalApprove, CashWithdrawalReject,
                    ExpenseListCreate, ExpenseDetail,
                    PLReportView, StaffSalesView, CashReconciliationView, ExpenseReportView,
                    ExtendStay, GrantGrace, ShiftRoom, GSTReportView, StayLogHistory,
                    ReservationReminderListCreate, ReservationReminderDetail)
from .auth_views import UserListCreate, UserDetail, GroupListCreate, GroupDetail, PermissionListView


urlpatterns = [
    path('room/types/', RoomTypeListCreate.as_view(), name='room-type-list-create'),
    path('room/types/<int:pk>/', RoomTypeDetail.as_view(), name='room-type-detail'),
    path('rooms/', RoomListCreate.as_view(), name='room-list-create'),
    path('room/<int:pk>/', RoomDetail.as_view(), name='room-detail'),
    path('room/<int:pk>/status-logs/', RoomStatusLogList.as_view(), name='room-status-logs'),
    path('country/codes/', CountryCodeListCreate.as_view(), name='country-code-list-create'),
    path('country/codes/<int:pk>/', CountryCodeDetail.as_view(), name='country-code-detail'),
    path('customers/', CustomerListCreate.as_view(), name='customer-list-create'),
    path('customers/<int:pk>/', CustomerDetail.as_view(), name='customer-detail'),
    path('configurations/', ConfigurationListCreate.as_view(), name='configuration-list-create'),
    path('configurations/<int:pk>/', ConfigurationDetail.as_view(), name='configuration-detail'),
    path('price/chart/', RoomsPriceChartListCreate.as_view(), name='price-chart-list-create'),
    path('price/chart/<int:pk>/', RoomsPriceChartDetail.as_view(), name='price-chart-detail'),
    path('stay-logs/', StayLogListActive.as_view(), name='stay-logs-active'),
    path('stay-logs/history/', StayLogHistory.as_view(), name='stay-logs-history'),
    path('stay-logs/<int:pk>/', StayLogDetail.as_view(), name='stay-log-detail'),
    path('stay-logs/<int:pk>/extend/', ExtendStay.as_view(), name='stay-log-extend'),
    path('stay-logs/<int:pk>/grace/', GrantGrace.as_view(), name='stay-log-grace'),
    path('stay-logs/<int:pk>/shift/', ShiftRoom.as_view(), name='stay-log-shift'),
    path('checkin/', Checkin.as_view(), name='checkin'),
    path('checkout/<int:pk>/', Checkout.as_view(), name='checkout'),
    path('group/customers/', group_customer, name='group-customers'),
    path('group/<int:group_id>/customers/', GroupCustomersView.as_view(), name='group-customers-list'),
    path('group/<int:group_id>/customers/add/', add_customers_to_group, name='group-customers-add'),
    path('group/<int:group_id>/customers/<int:customer_id>/remove/', remove_customer_from_group, name='group-customers-remove'),
    path('reservations/', ReservationListCreate.as_view(), name='reservation-list-create'),
    path('reservation/<int:pk>/', ReservationDetail.as_view(), name='reservation-detail'),
    path('amenities/', AmenityListCreate.as_view(), name='amenity-list-create'),
    path('amenities/<int:pk>/', AmenityDetail.as_view(), name='amenity-detail'),
    path('stay-logs/<int:log_id>/amenities/', StayLogAmenityListCreate.as_view(), name='stay-log-amenity-list-create'),
    path('stay-logs/amenities/<int:pk>/', StayLogAmenityDetail.as_view(), name='stay-log-amenity-detail'),
    path('stay-logs/<int:log_id>/payments/', StayLogPaymentListCreate.as_view(), name='stay-log-payment-list-create'),
    path('stay-logs/payments/<int:pk>/', StayLogPaymentDetail.as_view(), name='stay-log-payment-detail'),
    path('nc-requests/', NcRequestListCreate.as_view(), name='nc-request-list-create'),
    path('nc-requests/<int:pk>/', NcRequestDetail.as_view(), name='nc-request-detail'),
    path('nc-requests/<int:pk>/approve/', NcRequestApprove.as_view(), name='nc-request-approve'),
    path('nc-requests/<int:pk>/reject/', NcRequestReject.as_view(), name='nc-request-reject'),
    path('cash-withdrawals/', CashWithdrawalListCreate.as_view(), name='cash-withdrawal-list-create'),
    path('cash-withdrawals/<int:pk>/', CashWithdrawalDetail.as_view(), name='cash-withdrawal-detail'),
    path('cash-withdrawals/<int:pk>/approve/', CashWithdrawalApprove.as_view(), name='cash-withdrawal-approve'),
    path('cash-withdrawals/<int:pk>/reject/', CashWithdrawalReject.as_view(), name='cash-withdrawal-reject'),
    path('expenses/', ExpenseListCreate.as_view(), name='expense-list-create'),
    path('expenses/<int:pk>/', ExpenseDetail.as_view(), name='expense-detail'),
    path('reports/gst/', GSTReportView.as_view(), name='report-gst'),
    path('reports/revenue/', RevenueReportView.as_view(), name='report-revenue'),
    path('reports/occupancy/', OccupancyReportView.as_view(), name='report-occupancy'),
    path('reports/guests/', GuestReportView.as_view(), name='report-guests'),
    path('reports/today/', TodayOverviewView.as_view(), name='report-today'),
    path('reports/room-performance/', RoomPerformanceView.as_view(), name='report-room-performance'),
    path('reports/reservation-fulfillment/', ReservationFulfillmentView.as_view(), name='report-reservation-fulfillment'),
    path('reports/clv/', CLVReportView.as_view(), name='report-clv'),
    path('reports/trends/', TrendsReportView.as_view(), name='report-trends'),
    path('reports/stay-duration/', StayDurationView.as_view(), name='report-stay-duration'),
    path('reports/upsell/', UpsellReportView.as_view(), name='report-upsell'),
    path('reports/pipeline/', PipelineReportView.as_view(), name='report-pipeline'),
    path('finance/pl/', PLReportView.as_view(), name='finance-pl'),
    path('finance/staff-sales/', StaffSalesView.as_view(), name='finance-staff-sales'),
    path('finance/cash-reconciliation/', CashReconciliationView.as_view(), name='finance-cash-reconciliation'),
    path('finance/expenses/', ExpenseReportView.as_view(), name='finance-expenses'),
    path('reminders/', ReservationReminderListCreate.as_view(), name='reminder-list-create'),
    path('reminder/<int:pk>/', ReservationReminderDetail.as_view(), name='reminder-detail'),
    path('user/permissions/', UserPermissionsView.as_view(), name='user-permissions'),
    path('users/', UserListCreate.as_view(), name='user-list-create'),
    path('users/<int:pk>/', UserDetail.as_view(), name='user-detail'),
    path('groups/', GroupListCreate.as_view(), name='group-list-create'),
    path('groups/<int:pk>/', GroupDetail.as_view(), name='group-detail'),
    path('permissions/', PermissionListView.as_view(), name='permission-list')
]
